/**
 * Automated Golden Case Parity Verification Test (Node.js ESM).
 *
 * Verifies that the canonical JavaScript implementation (engine_v1.mjs)
 * matches the frozen golden cases in integration/golden_cases.json
 * generated by the canonical Python reference implementation.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { calculateRiskV1 } from "../../infrastructure/terraform/modules/cloud_api/lambda/risk/engine_v1.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "../..");

const goldenCasesPath = path.join(rootDir, "integration/golden_cases.json");
const goldenCases = JSON.parse(fs.readFileSync(goldenCasesPath, "utf-8"));

console.log(`Loaded ${goldenCases.length} golden cases for parity testing...`);

let passedCount = 0;
let failedCount = 0;

for (const testCase of goldenCases) {
  const { id, description, input, expected_output: expected } = testCase;
  const actual = calculateRiskV1(input, expected.location.district);

  let casePassed = true;
  const errors = [];

  // Check Flood score parity within 0.01 tolerance
  const floodScoreDiff = Math.abs(actual.flood.score - expected.flood.score);
  if (floodScoreDiff > 0.01) {
    casePassed = false;
    errors.push(`Flood score mismatch: actual=${actual.flood.score}, expected=${expected.flood.score} (diff=${floodScoreDiff})`);
  }

  // Check Flood band
  if (actual.flood.band !== expected.flood.band) {
    casePassed = false;
    errors.push(`Flood band mismatch: actual=${actual.flood.band}, expected=${expected.flood.band}`);
  }

  // Check Flood confidence within 0.01 tolerance
  const floodConfDiff = Math.abs(actual.flood.confidence - expected.flood.confidence);
  if (floodConfDiff > 0.01) {
    casePassed = false;
    errors.push(`Flood confidence mismatch: actual=${actual.flood.confidence}, expected=${expected.flood.confidence}`);
  }

  // Check Flood assessmentStatus
  if (actual.flood.assessmentStatus !== expected.flood.assessmentStatus) {
    casePassed = false;
    errors.push(`Flood assessmentStatus mismatch: actual=${actual.flood.assessmentStatus}, expected=${expected.flood.assessmentStatus}`);
  }

  // Check Flood water_depth & passability
  if (actual.flood.water_depth !== expected.flood.water_depth) {
    casePassed = false;
    errors.push(`Flood water_depth mismatch: actual=${actual.flood.water_depth}, expected=${expected.flood.water_depth}`);
  }
  if (actual.flood.passability !== expected.flood.passability) {
    casePassed = false;
    errors.push(`Flood passability mismatch: actual=${actual.flood.passability}, expected=${expected.flood.passability}`);
  }
  if (actual.flood.routePassability !== "UNDETERMINED") {
    casePassed = false;
    errors.push(`Flood routePassability must be UNDETERMINED: actual=${actual.flood.routePassability}`);
  }

  // Check Landslide score parity within 0.01 tolerance
  const lsScoreDiff = Math.abs(actual.landslide.score - expected.landslide.score);
  if (lsScoreDiff > 0.01) {
    casePassed = false;
    errors.push(`Landslide score mismatch: actual=${actual.landslide.score}, expected=${expected.landslide.score} (diff=${lsScoreDiff})`);
  }

  // Check Landslide band
  if (actual.landslide.band !== expected.landslide.band) {
    casePassed = false;
    errors.push(`Landslide band mismatch: actual=${actual.landslide.band}, expected=${expected.landslide.band}`);
  }

  // Check Landslide confidence within 0.01 tolerance
  const lsConfDiff = Math.abs(actual.landslide.confidence - expected.landslide.confidence);
  if (lsConfDiff > 0.01) {
    casePassed = false;
    errors.push(`Landslide confidence mismatch: actual=${actual.landslide.confidence}, expected=${expected.landslide.confidence}`);
  }

  // Check Landslide assessmentStatus
  if (actual.landslide.assessmentStatus !== expected.landslide.assessmentStatus) {
    casePassed = false;
    errors.push(`Landslide assessmentStatus mismatch: actual=${actual.landslide.assessmentStatus}, expected=${expected.landslide.assessmentStatus}`);
  }

  // Check Evidence status parity
  if (JSON.stringify(actual.flood.evidenceStatus) !== JSON.stringify(expected.flood.evidenceStatus)) {
    casePassed = false;
    errors.push(`Flood evidenceStatus mismatch: actual=${JSON.stringify(actual.flood.evidenceStatus)}, expected=${JSON.stringify(expected.flood.evidenceStatus)}`);
  }
  if (JSON.stringify(actual.landslide.evidenceStatus) !== JSON.stringify(expected.landslide.evidenceStatus)) {
    casePassed = false;
    errors.push(`Landslide evidenceStatus mismatch: actual=${JSON.stringify(actual.landslide.evidenceStatus)}, expected=${JSON.stringify(expected.landslide.evidenceStatus)}`);
  }

  // Check Model Version & Status
  if (actual.modelVersion !== "V1.0" || actual.modelStatus !== "PROVISIONAL") {
    casePassed = false;
    errors.push(`Model Version/Status mismatch: ${actual.modelVersion}/${actual.modelStatus}`);
  }

  if (casePassed) {
    console.log(`[PASS] ${id}: ${description}`);
    passedCount++;
  } else {
    console.error(`[FAIL] ${id}: ${description}`);
    for (const err of errors) {
      console.error(`       -> ${err}`);
    }
    failedCount++;
  }
}

console.log("\n==========================================");
console.log(`Parity Test Summary: ${passedCount} passed, ${failedCount} failed of ${goldenCases.length} total.`);
console.log("==========================================");

if (failedCount > 0) {
  process.exit(1);
} else {
  console.log("SUCCESS: 100% Python-to-JavaScript Lambda parity verified across all golden cases.");
}
